#!/bin/sh

# diy_part.sh中的UCI设置
[ -f /etc/default_uci ] && chmod +x /etc/default_uci && source /etc/default_uci
/etc/init.d/network restart

# 去除coremark定时任务
count=$(grep -c "coremark" /etc/crontabs/root)
if [ "$count" -eq 1 ]; then
    sed -i '/coremark/d' /etc/crontabs/root
fi

if [ -f "/usr/lib/lua/luci/controller/ttyd.lua" ]; then
    sed -i 's?services?system?g' "/usr/lib/lua/luci/controller/ttyd.lua"
fi

# 修复部分自启动服务、插件无运行权限的bug
for file in /etc/init.d/*; do
    chmod +x "$file"
done

# 删除 /etc/opkg/distfeeds.conf 中的特定字符串
patterns="openwrt_custom helloworld ssrplus passwall OpenClash"
for pattern in $patterns; do
    sed -i "/$pattern/d" /etc/opkg/distfeeds.conf
done

luci_web=/usr/lib/lua/luci/view/admin_status/index.htm
if [ -f "/etc/index.htm" ]; then
    sed -i 's#localtime  = .*#localtime  = os.date("%Y-%m-%d") .. " " .. os.date("%X") .. " " .. translate(os.date("%A")),#g' "/etc/index.htm"
elif [ -f "${luci_web}" ]; then
    sed -i 's#localtime  = .*#localtime  = os.date("%Y-%m-%d") .. " " .. os.date("%X") .. " " .. translate(os.date("%A")),#g' "${luci_web}"
fi

if [ -f "/etc/index.htm" ]; then
    count=$(grep -c "(<%=pcdata(ver.luciversion)%>)" "/etc/index.htm")
    if [ "$count" -eq 1 ]; then
        sed -i 's?(<%=pcdata(ver.luciversion)%>)?- <%=pcdata(ver.luciversion)%>?g' "/etc/index.htm"
    fi
elif [ -f "${luci_web}" ]; then
    count=$(grep -c "(<%=pcdata(ver.luciversion)%>)" "${luci_web}")
    if [ "$count" -eq 1 ]; then
        sed -i 's?(<%=pcdata(ver.luciversion)%>)?- <%=pcdata(ver.luciversion)%>?g' "${luci_web}"
    fi
fi

sed -i 's?=== WARNING! =====================================?=================== WARNING! ====================?g' /etc/profile

if [ -n "$(grep "downloads.openwrt.org" /etc/opkg/distfeeds.conf)" ]; then
    sed -i 's?downloads.openwrt.org?mirrors.cloud.tencent.com/openwrt?g' /etc/opkg/distfeeds.conf
fi